### ISSUE TITLE
[Windows][Powershell7] cannot find type `PathBuf` in this scope

### ISSUE THREAD

**Issue by searleser97** [noib3/nvim-oxi#119]
![image](https://github.com/noib3/nvim-oxi/assets/5056411/8b6a5ce8-b399-481e-95b5-8121009d1b65)
##### `lib.rs`
```rs
use nvim_oxi as oxi;

#[oxi::module]
fn foo() -> oxi::Result<i32> {
    Ok(42)
}
```

##### `Cargo.toml`
```toml
[package]
name = "lua_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
nvim-oxi = { version = "0.3", features = ["neovim-nightly"] }
```

Rust versions
cargo 1.76.0-nightly (978722961 2023-12-06)
rustc 1.76.0-nightly (1fdfe1234 2023-12-06)
