### ISSUE TITLE
[Ubuntu] Error while calling lua chunk... undefined symbol: luaopen_...

### ISSUE THREAD

**Issue by searleser97** [noib3/nvim-oxi#121]
### Error

![image](https://github.com/noib3/nvim-oxi/assets/5056411/27502545-aa79-4481-a5cd-313a00b5f124)

### File Structure

![image](https://github.com/noib3/nvim-oxi/assets/5056411/9bddcbe5-e3be-46fb-81eb-aa759e1d9a7d)

#### Cargo.toml
```toml
[package]
name = "lua_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
nvim-oxi = { git = "https://github.com/noib3/nvim-oxi", features = ["neovim-nightly"] }
```

#### lib.rs
```rs
use nvim_oxi as oxi;

#[oxi::module]
fn foo() -> oxi::Result<i32> {
    Ok(42)
}
```

#### init.lua
```lua
require("settings")
require("plugins")
require("mappings")
require("lsp")
require("parsers")

require("lua_utils")
```
