### ISSUE TITLE
Crash when loading the example plugin on Windows

### ISSUE THREAD

**Issue by AregevDev** [noib3/nvim-oxi#125]
Hello,
I am using the crate setup example from the repo and Neovim crashes when loading the plugin DLL file by requiring the module. I am copying the DLL directly to NeoVim's `bin` directory.

The nvim process crashes with virtually no way to debug it.
I tried the latest git version of `nvim-oxi`.
I am on Windows, I added the `/force:UNRESOLVED` flags to my cargo config:
```toml
[target.x86_64-pc-windows-msvc]
rustflags = [
  "-C", "link-arg=/FORCE:UNRESOLVED",
]

[target.aarch64-pc-windows-msvc]
rustflags = [
  "-C", "link-arg=/FORCE:UNRESOLVED",
]
```
