### ISSUE TITLE
Test macro doesn't seem to pick up on failures

### ISSUE THREAD

**Issue by turboladen** [noib3/nvim-oxi#126]
I'm not sure if I'm just missing something or not, but it seems like the `#[nvim_oxi::test]` macro isn't doing anything for me.

```rust
pub fn is_pum_visible() -> nvim_oxi::Result<bool> {
    let result: u32 = nvim_oxi::api::call_function("pumvisible", nvim_oxi::Array::new())?;

    if result == 0 {
        Ok(false)
    } else {
        Ok(true)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    use nvim_oxi::{self as oxi};

    #[oxi::test]
    fn is_pum_visible_test() {
        eprint!("hi");
        assert!(is_pum_visible().unwrap());
        panic!("hi");
    }
}
```
I then run `cargo build` and `cargo test` and get:

```
running 1 test
test tests::is_pum_visible_test ... ok
```

My test, of course, initially didn't have the `eprintln!()` or `panic!()` calls--I just added those to get the test to fail, which it didn't.

---

- nvim-oxi: 0.4.1
- NVIM v0.9.5
- Build type: Release
- LuaJIT 2.1.1703358377
- Rust 1.75.0
- MacOS 14.2.1

**Comment by noib3** [comment]
I can reproduce this if I run it as a unit test.

Is that file your `lib.rs`? Could you also post the `Cargo.toml`? I'll try debugging this tomorrow.

**Comment by turboladen** [comment]
It is my `lib.rs`, yes. On my mobile right now, but I’ll post the Cargo.toml as soon as I get in front of a computer.On Jan 24, 2024, at 2:04 PM, Riccardo Mazzarini ***@***.***> wrote:﻿
I can reproduce this if I run it as a unit test.
Is that file your lib.rs? Could you also post the Cargo.toml? I'll try debugging this tomorrow.

**Comment by turboladen** [comment]
Ok, so I'm working in a multi-crate workspace; dunno if that changes anything. Here's the workspace `Cargo.toml`:

```toml
[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
log = "0.4"
nvim-oxi = { version = "0.4.1", features = ["neovim-0-9"] }
```

And the `Cargo.toml` from the crate I was adding tests for:

```toml
[package]
name = "nvim-sous_chef-complete_fn"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
log.workspace = true
nvim-oxi.workspace = true

[dev-dependencies]
nvim-oxi = { workspace = true, features = ["test"] }
```

FWIW, if I don't scope my test module to `#[cfg(test)]`, tests works as expected, so in the meantime, I've been getting by just fine like that (not ideal in the long run, of course).
