### ISSUE TITLE
Failed to resolve: could not find `plugin` in `nvim_oxi`

### ISSUE THREAD

**Issue by javiorfo** [noib3/nvim-oxi#153]
Hello,
Are the examples updated? -> [nvim-oxi examples](https://github.com/noib3/nvim-oxi/tree/main/examples)

The documentation only shows module and test macros

I can use **[nvim_oxi::module]** macro but not **[nvim_oxi::plugin]**

This is a simple example with my conf which builds correctly:
```toml
[package]
name = "mylib"
version = "0.1.0"
edition = "2021"

[lib]
name = "mylib"
crate-type = ["cdylib"]

[dependencies]
nvim-oxi = { version = "0.4.2", features = [ "neovim-0-9", "libuv" ] }
```

In that case, please update the examples.
Thanks
