### ISSUE TITLE
Version `0.4.2` gives me compilation errors

### ISSUE THREAD

**Issue by patata3000** [noib3/nvim-oxi#156]
Hello, I just ran `cargo update` and got compilation error with version `0.4.2`.

This is my cargo toml:

```toml
[package]
name = "mypackage"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
log = "*"
log4rs = "*"
mlua = { version = "*", features = ["luajit", "serialize"] }
ndarray = "0.15.6"
nvim-oxi = { version = "*", features = [
  # "neovim-nightly",
  "libuv",
  "mlua",
  "neovim-0-9",
  "miniserde",
] }
oxi-types = "*"
oxi-libuv = "*"
rand = { version = "*" }
serde = { version = "*", features = ["derive"] }
serde_json = "*"
thiserror = "1.0.57"
tokio = { version = "1.36.0", features = ["full"] }
tokio-util = { version = "0.7.10", features = ["compat"] }
uuid = { version = "*", features = ["v4", "macro-diagnostics", "serde"] }

itertools = "0.12.1"
```

The errors I get
```log
[$] cargo update
    Updating crates.io index
    Updating backtrace v0.3.69 -> v0.3.71
    Updating bumpalo v3.14.0 -> v3.15.4
    Updating core-foundation-sys v0.8.4 -> v0.8.6
    Updating hermit-abi v0.3.5 -> v0.3.9
    Updating js-sys v0.3.67 -> v0.3.69
    Updating nvim-oxi v0.4.1 -> v0.4.2
    Updating oxi-api v0.4.1 -> v0.4.2
    Updating oxi-libuv v0.4.1 -> v0.4.2
    Updating oxi-types v0.4.1 -> v0.4.2
    Updating polling v3.5.0 -> v3.6.0
    Updating wasm-bindgen v0.2.90 -> v0.2.92
    Updating wasm-bindgen-backend v0.2.90 -> v0.2.92
    Updating wasm-bindgen-futures v0.4.40 -> v0.4.42
    Updating wasm-bindgen-macro v0.2.90 -> v0.2.92
    Updating wasm-bindgen-macro-support v0.2.90 -> v0.2.92
    Updating wasm-bindgen-shared v0.2.90 -> v0.2.92
    Updating web-sys v0.3.67 -> v0.3.69
    Updating windows-targets v0.52.0 -> v0.52.4
    Updating windows_aarch64_gnullvm v0.52.0 -> v0.52.4
    Updating windows_aarch64_msvc v0.52.0 -> v0.52.4
    Updating windows_i686_gnu v0.52.0 -> v0.52.4
    Updating windows_i686_msvc v0.52.0 -> v0.52.4
    Updating windows_x86_64_gnu v0.52.0 -> v0.52.4
    Updating windows_x86_64_gnullvm v0.52.0 -> v0.52.4
    Updating windows_x86_64_msvc v0.52.0 -> v0.52.4

[$] ta install-online && nv test.sql
task: [install-online] cargo build
   Compiling oxi-api v0.4.2
error[E0407]: method `filepath` is not a member of trait `From`
  --> $HOME/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/oxi-api-0.4.2/src/types/context_type.rs:27:5
   |
27 | /     fn filepath(ctx: ContextType) -> Self {
28 | |         nvim::String::from_object(
29 | |             ctx.serialize(Serializer::new())
30 | |                 .expect("`ContextType` is serializable"),
31 | |         )
32 | |         .expect("`ContextType` is serialized into a string")
33 | |     }
   | |_____^ not a member of trait `From`

error[E0407]: method `filepath` is not a member of trait `From`
  --> $HOME/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/oxi-api-0.4.2/src/types/window_style.rs:12:5
   |
12 | /     fn filepath(style: WindowStyle) -> Self {
13 | |         match style {
14 | |             WindowStyle::Minimal => "minimal",
15 | |         }
16 | |         .into()
17 | |     }
   | |_____^ not a member of trait `From`

error[E0407]: method `filepath` is not a member of trait `From`
  --> $HOME/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/oxi-api-0.4.2/src/types/window_style.rs:21:5
   |
21 | /     fn filepath(style: WindowStyle) -> Self {
22 | |         NvimString::filepath(style).into()
23 | |     }
   | |_____^ not a member of trait `From`

error[E0046]: not all trait items implemented, missing: `from`
  --> $HOME/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/oxi-api-0.4.2/src/types/context_type.rs:26:1
   |
26 | impl From<ContextType> for nvim::String {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `from` in implementation
   |
   = help: implement the missing item: `fn from(_: context_type::ContextType) -> Self { todo!() }`

error[E0046]: not all trait items implemented, missing: `from`
  --> $HOME/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/oxi-api-0.4.2/src/types/window_style.rs:11:1
   |
11 | impl From<WindowStyle> for NvimString {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `from` in implementation
   |
   = help: implement the missing item: `fn from(_: window_style::WindowStyle) -> Self { todo!() }`

error[E0046]: not all trait items implemented, missing: `from`
  --> $HOME/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/oxi-api-0.4.2/src/types/window_style.rs:20:1
   |
20 | impl From<WindowStyle> for Object {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `from` in implementation
   |
   = help: implement the missing item: `fn from(_: window_style::WindowStyle) -> Self { todo!() }`

error[E0599]: no function or associated item named `filepath` found for struct `oxi_types::String` in the current scope
  --> $HOME/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/oxi-api-0.4.2/src/types/window_style.rs:22:21
   |
22 |         NvimString::filepath(style).into()
   |                     ^^^^^^^^ function or associated item not found in `String`
   |
note: if you're trying to build a new `oxi_types::String` consider using one of the following associated functions:
      oxi_types::String::from_bytes
      oxi_types::String::new
  --> $HOME/.local/share/cargo/registry/src/index.crates.io-6f17d22bba15001f/oxi-types-0.4.2/src/string.rs:65:5
   |
65 |     pub fn from_bytes(bytes: &[u8]) -> Self {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
96 |     pub fn new() -> Self {
   |     ^^^^^^^^^^^^^^^^^^^^

Some errors have detailed explanations: E0046, E0407, E0599.
For more information about an error, try `rustc --explain E0046`.
error: could not compile `oxi-api` (lib) due to 7 previous errors
task: Failed to run task "install-online": exit status 101
```
