### ISSUE TITLE
`set_hl` not applies color (set highlight problem)

### ISSUE THREAD

**Issue by RAprogramm** [noib3/nvim-oxi#187]
```rust
    let header_highlight = nvim_oxi::api::opts::SetHighlightOpts::builder()
        .foreground("#FF0000")
        .strikethrough(true)
        .bold(true)
        .build();

    handle_error(
        nvim_oxi::api::set_hl(0, "Header", &header_highlight),
        "Failed to set highlight for Header",
    )?;
```
in neovim's cmd line:
```vim
:hi Header                                                                                                                                                                                                
Header xxx cterm=bold,strikethrough gui=bold,strikethrough   
```

when i try to set highlights colors not apply.

like that in the `Cargo.toml`:

```toml
...
[dependencies]
nvim-oxi = { version = "0.5.1", features = ["neovim-0-10", "test", "neovim-nightly"] }
...
```
