### ISSUE TITLE
The calc example is broken

### ISSUE THREAD

**Issue by Avimitin** [noib3/nvim-oxi#62]
Copy the calc example and build it, then copy the .so file to lua directory, and then setup the rtp path and call the add or multiply function, got totally wrong result:

Example test script:

```vim
execute ':set rtp+=' . expand("%:p:h")
" I am testing in a crate named playground, it doesn't matter
lua =require("playground").add(1, 1)
lua =require("playground").multiply(1, 1)
```

Got:

```text
1
0
```

Cargo.toml

```toml
[package]
name = "playground"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nvim-oxi = { git = "https://github.com/noib3/nvim-oxi", features = ["nightly"] }

[lib]
crate-type = ["cdylib"]
```
