### ISSUE TITLE
could not find `test` in `oxi`could not find `test` in `oxi`

### ISSUE THREAD

**Issue by yuki-uthman** [noib3/nvim-oxi#93]
Hello!

So far api and calc example worked as expected and I think it is super coooool.
But I do not know how to make the nvim_oxi::test macro work.
I am not sure if i am asking something stupid here because I am new to rust.

```rust
use nvim_oxi::{self as oxi, api};

#[oxi::test]
fn set_get_del_var() {
    api::set_var("foo", 42).unwrap();
    assert_eq!(Ok(42), api::get_var("foo"));
    assert_eq!(Ok(()), api::del_var("foo"));
}
```

The compiler complains that it cannot find test under nvim_oxi.
```rust
error[E0433]: failed to resolve: could not find `test` in `oxi`
 --> tests/test.rs:4:8
  |
  | #[oxi::test]
  |        ^^^^ could not find `test` in `oxi`
```

Cargo.toml
```toml
[lib]
crate-type = ["cdylib"]

[dependencies.nvim-oxi]
version = "0.2.2"
features = ["neovim-0-7"]
```

Thank you again for your awesome work!
